[env:esp32dev]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
upload_speed = 115200
monitor_speed = 9600
upload_protocol = esptool
upload_port = COM7
monitor_port = COM7
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  knolleary/PubSubClient@^2.8
  adafruit/Adafruit NeoPixel@^1.12.5
  dfrobot/DFRobotDFPlayerMini@^1.0.6
